### ISSUE TITLE
this command error : python3 scripts/train_eval.py --eval path-to-model.h5

### ISSUE THREAD

**Issue by SeaFu** [JakubSochor/BoxCars#11]
Excused me,I follow your step but show the error follow as:

![_002](https://user-images.githubusercontent.com/42667670/44571501-7e045d80-a7b3-11e8-93e4-1c7fb4d8b968.png)
![_003](https://user-images.githubusercontent.com/42667670/44571502-7e9cf400-a7b3-11e8-8eca-156c7fde8d0b.png)

how can I fix this error

**Comment by JakubSochor** [comment]
Hi, you have most likely wrong version of CUDA. The code uses older version
of tensorflow. Either try to update tensorflow or install also the older
version of CUDA (and libcudnn).

**Comment by SeaFu** [comment]
Can you tell me which version of your CUDA and libcudnn

**Comment by suraj2596** [comment]
Use CUDA 8 with libcudnn 5.1.
