### ISSUE TITLE
Help in understanding dataset.pkl

### ISSUE THREAD

**Issue by suraj2596** [JakubSochor/BoxCars#12]
Hello,

I'm trying to get the direction of VP's so that I can make a 3DBB. So, as mentioned in the paper's fig 7, I made the model to predict the direction of vanishing points by predicting a set of 3 angles.

```
{'098': {'pp': array([ 427.5,  240.5]),
   'vp1': array([ 948.281 ,   92.7385]),
   'vp3': array([  455.78606968,  5066.38864576]),
   'focal': 835.6732001667876,
   'vp2': array([-952.23 ,  103.878])}
```

This is an example of a camera's properties taken from dataset.pkl. As mentioned in the paper, I expected a set of 3 angles to be given in the dataset each corresponding to a VP. But it seems a set of numbers are given corresponding to each VP. I'm confused here.

1. What are those numbers?
2. How do I proceed from here to construct the 3DBB?

Can someone help me out in understanding this?

Thanks in advance!

**Comment by suraj2596** [comment]
So, I took the vp's as pairs of coordinates and plotted 3 lines, each starting from the center. Each of these lines indicate the direction towards a VP. 

To my understanding, The edges of the bounding boxes must be parallel to the direction of VPs.

For some, it seems fine: 
![screenshot from 2018-09-04 18-15-30](https://user-images.githubusercontent.com/5541472/45155231-e9105400-b1f7-11e8-8739-2183c0e6e0dc.png)

But for few, it's not.

![download](https://user-images.githubusercontent.com/5541472/45155599-2e815100-b1f9-11e8-8989-c433497671ab.png)

Am I missing anything here?

**Comment by JakubSochor** [comment]
The easiest and safest way how to compute the 2D image coordinates of the vanishing points is to use intersection of lines on the 3D bounding box which should be parallel. I have always done it like this when I was working with the dataset.

It is possible that the the crop offset is not taken into account for the position of the vanishing points for some videos (the ones with non numeric name). These were the first videos which we processed and the dataset was extended after that. Therefore, it is possible that we have an inconsistency in the coordinates of the vanishing points.

**Comment by suraj2596** [comment]
Thank you! That cleared my doubt.
