### ISSUE TITLE
No such file :dataset.pkl

### ISSUE THREAD

**Issue by SeaFu** [JakubSochor/BoxCars#13]
![zzz 525-4 -boxcars_005](https://user-images.githubusercontent.com/42667670/45147487-98006000-b1f7-11e8-8ce0-5026dab159e7.png)

**Comment by suraj2596** [comment]
Change this variable in `config.py` to where you downloaded the dataset.
`BOXCARS_DATASET_ROOT = "/path/to/location/Datasets/BoxCars116k/"`
