### ISSUE TITLE
Where to find the NET that estimates 3D bb ? 

### ISSUE THREAD

**Issue by jediofgever** [JakubSochor/BoxCars#15]
Hello , Thank you for this interesting research. So far I have been playing with this repository and I was able to reproduce the results in the paper. 

I am more intersted in the part that you are estimating 3D bounding boxes, However in the paper and in the repository I couldnt find any clue about how to use that independently , Can you please summuarize or list some link that could help me to understand 3D bb estimation part 

Thank you in advance,

**Comment by JakubSochor** [comment]
Unfortunately, I do not have the network for VP estimation anymore. But it is not hard to train one. 
When you have the contour and the vanishing points of the vehicle, you just need to construct the 3DBB. 
The method for construction is described here: https://medusa.fit.vutbr.cz/traffic/research-topics/traffic-camera-calibration/automatic-camera-calibration-for-traffic-understanding-bmvc-2014/

**Comment by JakubSochor** [comment]
Also the details how to construct the VPs and contour are here: https://medusa.fit.vutbr.cz/traffic/research-topics/fine-grained-vehicle-recognition/boxcars-improving-vehicle-fine-grained-recognition-using-3d-bounding-boxes-in-traffic-surveillance/
