### ISSUE TITLE
How to show the detected image ?

### ISSUE THREAD

**Issue by ACkuku** [JakubSochor/BoxCars#2]
hello, I was followed the README.md, and got the final_model.h5, but if I want to detect one image using the final_model.h5, how to show the results of the detection, it's like the 3D bounding box on the image(Fig.5 in your Paper). Thank you.

**Comment by JakubSochor** [comment]
You can find the 3D bounding box in the dataset. See get_vehicle_instance_data in lib/boxcars_dataset.py.
Then you need to draw lines between these points to draw the 3D bounding box. See Fig. 2 for ordering of those points. You can use for matplotlib for that.

**Comment by ACkuku** [comment]
Thank you, I print the bb3d(get_vehicle_instance_data in lib/boxcars_dataset.py ), and draw 3D bounding box on image. but if I detect other image not in the dataset,  there was no bb3d. I don't know why.

**Comment by JakubSochor** [comment]
What do you mean by other image? Where did you get that image?

**Comment by ACkuku** [comment]
Sorry, the image not in dataset, I just want to test one image that downloaded by the Internet, for example, one picture include a car,  I want to test the 3D bounding box on the picture.

**Comment by JakubSochor** [comment]
I see.
Well, in that case you have two options. The first one is to draw the 3DBB manually if you want to try it only on a few samples. Or you can follow the proposed method in Section 3.4 (Fig. 5). We have not published the source codes to that part, so you would need to implement it.
