### ISSUE TITLE
Link to dataset is down

### ISSUE THREAD

**Issue by bernharl** [JakubSochor/BoxCars#21]
I get an error on two different internet connections while trying to access [this](https://medusa.fit.vutbr.cz/traffic/data/BoxCars116k.zip) link to download the dataset. Is this a temporary issue?

**Comment by JakubSochor** [comment]
Unfortunately, the server that is hosting the dataset is down for
maintenance. Hopefully, it will be back up next week.

**Comment by bernharl** [comment]
It is still not online. Any updates? :)

**Comment by JakubSochor** [comment]
I added Jakub Špaňhel to CC who will have more information about it.

**Comment by achilleess** [comment]
Hi, has the problem resolved? I am still not able to download dataset

**Comment by JakubSochor** [comment]
+Jakub Špaňhel <ispanhel@fit.vutbr.cz>

**Comment by 109021017** [comment]
Would you please upload the dataset to the Google Drive or some where?

**Comment by JakubSochor** [comment]
+Roman Juranek <ijuranek@fit.vutbr.cz> is working on bringing up the server
back up. Therefore, I suggest to wait for that since the dataset is not
exactly small.

**Comment by SAN4EZ7714** [comment]
I also need this dataset. Can you temporarily give access from another source?

And link on models also be helpful.
https://medusa.fit.vutbr.cz/traffic/data/BoxCars-models/

**Comment by JakubSochor** [comment]
+Jakub Špaňhel +Roman Juránek

Jakub and Roman, can you please send a link to the dataset? 

Jakub

**Comment by harshab1701** [comment]
Hello,

**Comment by harshab1701** [comment]
The dataset would benefit greatly in my research but the link to access the dataset is still down. Is there any other ways to access the data ?

**Comment by JakubSochor** [comment]
The dataset is now available also at https://drive.google.com/file/d/19LHLOmmVyUS1R4ypwByfrV8KQWnz2GDT/view?usp=sharing

**Comment by harshab1701** [comment]
Thank you so much. I really appreciate it!!

**Comment by TheGhostFish** [comment]
Can you provide a backup link for pre-trained models too ?
Thanks so much
