### ISSUE TITLE
Dataset link is down

### ISSUE THREAD

**Issue by Novare** [JakubSochor/BoxCars#27]
Hi,
the link to the dataset (https://medusa.fit.vutbr.cz/traffic/data/BoxCars116k.zip) is down. Can you put that one up again or provide a mirror? Thanks!

**Comment by JakubSochor** [comment]
In the links section in the readme is a backup location to the dataset.
https://github.com/JakubSochor/BoxCars

**Comment by Novare** [comment]
You're right, I overlooked that. Thanks! Closing.
