### ISSUE TITLE
what's the coordinate of the image

### ISSUE THREAD

**Issue by mandrend** [JakubSochor/BoxCars#3]
I see that in your article, you set the principle point be the middle of the image, and in the dataset.pkl, every camera's PP cordiante is[ 427.5,  240.5], so it confuse me with the coordinate of the image。

**Comment by JakubSochor** [comment]
We always added 0.5 to the image center (for better handling of infinity in diamond space). So the resolution of the camera with PP in [427.5, 240.5] is 854x480.

**Comment by mandrend** [comment]
@JakubSochor Thanks for your answer.
