### ISSUE TITLE
About how to estimate the 3DBB

### ISSUE THREAD

**Issue by MiniBullLab** [JakubSochor/BoxCars#5]
I am confused about how to estimate the 3D bounding box with the contour of the vehicles and the direction of the VP. I also wonder the input when using CNN for estimation of directions towards vanishing points, the whole image with several car or the cropped image with only a car?

**Comment by JakubSochor** [comment]
Hi, what is not clear? 
How to estimate the contour and the directions towards vanishing points? 
Or the 3D bounding box construction after that? The 3DBB construction is the same as in the original 3DBB paper https://medusa.fit.vutbr.cz/traffic/data/papers/2014-BMVC-BoundingBoxes.pdf
We use cropped vehicle images as an input to the CNN which estimates the directions towards VPs.

**Comment by MiniBullLab** [comment]
ok, i understand, thank you
