### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by rigolepe** [JakubSochor/BoxCars#6]
Which license does this project have? 

cheers,
   Peter

**Comment by JakubSochor** [comment]
Hi, 
it is possible to use the dataset and the source code for research and non-commercial purposes. If your usage fits into that, you can modify it freely. Just cite the paper if you publish a paper and use the dataset or source code. 

In case you want to use the dataset or source code for commercial purposes, it is necessary to get a license from Brno University of Technology to do that. 
If you want to discuss the commercial license, it is better to do it over email http://www.fit.vutbr.cz/~isochor/

Jakub
