### ISSUE TITLE
how Accuracy is measured?

### ISSUE THREAD

**Issue by SahadevPoudel** [JakubSochor/BoxCars#8]
In this system, How Accuracy is measured? Please explain me

**Comment by JakubSochor** [comment]
The accuracy is measured as number of correctly recognized images (tracks) divided by the number of all images (tracks). Check this function for further details. 
https://github.com/JakubSochor/BoxCars/blob/b7392f0d9b74e352d76dee300a89287aae9f9eab/lib/boxcars_dataset.py#L90
