### ISSUE TITLE
lots of wrong labeled images in the training boxcars116k dataset

### ISSUE THREAD

**Issue by ruizengalways** [JakubSochor/BoxCars#9]
Till now, I find following images are wrong-labeled.  Would you please tell me how to automatically filter out such sort of outliers in the dataset.

wrong_labeled_image_ids = [520, 687, 8698, 1410, 4734, 5667, 33492]

`    # Load image 
    wrong_labeled_image_id  = wrong_labeled_image_ids [0]
    vehicle_id, instance_id = dataset.X[wrong_labeled_image_id ]
    class_ids = [dataset.Y[image_id]]
    class_ids = np.array(class_ids, dtype=np.int32)

    # Get corresponding data
    vehicle, instance, bb3d, bb2d = dataset.get_vehicle_instance_data(vehicle_id, instance_id)
    image = dataset.get_image(vehicle_id, instance_id)`

when we map the bb2d and bb3d onto the original image, we can get following image
![image](https://user-images.githubusercontent.com/9302805/42721703-b632cf80-8782-11e8-933b-c202ccd5daf3.png)

Some more wrong-labeled images:
Image ID: 4734
![image](https://user-images.githubusercontent.com/9302805/42721710-d3f671c0-8782-11e8-98ae-32d164256d2d.png)

Image ID: 1410
![image](https://user-images.githubusercontent.com/9302805/42721715-e471aff6-8782-11e8-892c-362e63325e11.png)

**Comment by JakubSochor** [comment]
The detections of the vehicles were produced automatically; therefore, it is possible that some of the detections are not accurate and can be misaligned. I am not aware of any method which can solve this problem automatically.
